version: '3.8'

services:
  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8001:8000"
    volumes:
      - ./chroma-data:/data 

  datadog:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    ports:
      - "4318:4318"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=us5.datadoghq.com
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro 
      - /var/lib/docker/containers:/var/lib/docker/containers:ro       